print(all([1]))
print(all(set([1])))
print(all({}))
print(all({1:'one'}))
print(all([[]]))
print(all([6,0,7]))
print(all([1,2,5]))
print(all([4, {5}, [8]]))
print()
print(any([]))
print(any([[]]))
print(any([0]))
print(any([1]))
print(any([1,0,5]))
print(any([4,5,6]))
print(any([1, {4}, [4]]))
